[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1" }
serde_json = "1"
sea-orm = { version = "1.1.7", features = [
  "runtime-tokio-native-tls",
  "sqlx-sqlite",
] }
ts-rs = "10.1.0"
