// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppStrucDir = { 
/**
 * 结构的根目录 
 */
base: string, 
/**
 * 备份目录 
 */
backup: string, 
/**
 * 配置文件目录 
 */
config: string, 
/**
 * 数据库目录 
 */
database: string, 
/**
 * 媒体库目录 
 */
media: string, 
/**
 * 模型库目录 
 */
model: string, 
/**
 * 缩略图目录 
 */
thumbnail: string, };
