// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppStrucDir } from "./AppStrucDir";

/**
 * 前后端共享的配置的结构 
 */
export type GlobalConfig = { struc: AppStrucDir, };
